go_import_path: github.com/redhat-developer/service-binding-operator
sudo: required
dist: xenial
language: go

go:
- 1.13.x

env:
  global:
    - SDK_VERSION="0.8.1"
    - GO111MODULE=on

before_install:
# Download Operator SDK
- curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v${SDK_VERSION}/operator-sdk-v${SDK_VERSION}-x86_64-linux-gnu && chmod +x operator-sdk && mv operator-sdk $GOPATH/bin/

script:
# Run merge-to-master-release
- if [ "$TRAVIS_BRANCH" = "testing-quay" ]; then
  make merge-to-master-release; fi
